export const ENABLE_FULL_SCREEN = 'ENABLE_FULL_SCREEN';
export const DISABLE_FULL_SCREEN = 'DISABLE_FULL_SCREEN'; 
export const TOGGLE_FULL_SCREEN = 'TOGGLE_FULL_SCREEN'; 
export const ENABLE_IMAGE_LOADER = 'ENABLE_IMAGE_LOADER'; 
export const DISABLE_IMAGE_LOADER = 'DISABLE_IMAGE_LOADER'; 

export const CLOSE_LIGHTBOX = 'CLOSE_LIGHTBOX';
export const LOAD_NEXT_IMAGE = 'LOAD_NEXT_IMAGE';
export const LOAD_PREV_IMAGE = 'LOAD_PREV_IMAGE';
export const TOGGLE_FULL_SCREEN_LIGHTBOX = 'TOGGLE_FULL_SCREEN_LIGHTBOX';
