export const OPEN_FILMSTRIP = 'OPEN_FILMSTRIP';
export const CLOSE_FILMSTRIP = 'CLOSE_FILMSTRIP';
export const SHOW_FILMSTRIP_BUTTON = 'SHOW_FILMSTRIP_BUTTON';
export const HIDE_FILMSTRIP_BUTTON = 'CLOSE_FILMSTRIP_BUTTON';

export const SHOW_FLASH_CODE = 'SHOW_FLASH_CODE';
export const CLOSE_FLASH_CODE = 'CLOSE_FLASH_CODE';
export const RECEIVE_SHORT_LINK = 'RECEIVE_SHORT_LINK';

export const SHOW_FLASH_CODE_BUTTON = 'SHOW_FLASH_CODE_BUTTON';
export const HIDE_FLASH_CODE_BUTTON = 'HIDE_FLASH_CODE_BUTTON';

export const ENABLE_FULL_SCREEN = 'ENABLE_FULL_SCREEN';
export const DISABLE_FULL_SCREEN = 'DISABLE_FULL_SCREEN'; 
export const OPEN_LIGHTBOX = 'OPEN_LIGHTBOX';
export const CLOSE_LIGHTBOX = 'CLOSE_LIGHTBOX';
export const TOGGLE_FULL_SCREEN_LIGHTBOX = 'TOGGLE_FULL_SCREEN_LIGHTBOX';
export const IMAGE_LOADED_IN_LIGHTBOX = 'IMAGE_LOADED_IN_LIGHTBOX';
export const IMAGE_LOADING_START_IN_LIGHTBOX = 'IMAGE_LOADING_START_IN_LIGHTBOX';

export const CLOSE_WELCOME_POPIN = 'WELCOME_POPIN/CLOSE';
export const OPEN_WELCOME_POPIN = 'WELCOME_POPIN/OPEN';

export const SELECT_MEDIUM = 'SELECT_MEDIUM';
export const UNSELECT_MEDIUM = 'UNSELECT_MEDIUM';
export const IO_SELECT_MEDIUM = 'IO/SELECT_MEDIUM';
export const IO_JOIN_ROOM = 'IO/JOIN_ROOM';
export const RECEIVE_MEDIA = 'RECEIVE_MEDIA';
export const RECEIVE_ROOM_ID = 'RECEIVE_ROOM_ID';
export const JOIN_ROOM = 'JOIN_ROOM';

