export default {
    SHOW_FLASH_CODE:  'FLASHCODE/SHOW',
    CLOSE_FLASH_CODE: 'FLASHCODE/CLOSE',
    FETCH_SHORT_LINK_REQUESTED: 'FLASHCODE/FETCH_SHORT_LINK_REQUESTED',
    FETCH_SHORT_LINK_SUCCEEDED: 'FLASHCODE/FETCH_SHORT_LINK_SUCCEEDED',
    FETCH_SHORT_LINK_FAILED: 'FLASHCODE/FETCH_SHORT_LINK_FAILED',
};
